version: '2'
services:
  postgres:
    image: postgres:9.4
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=theia"
      - "POSTGRES_PASSWORD=theia"

  redis:
    image: redis:5.0.3-stretch
    command: redis-server --appendonly yes

  app:
    build:
      context: .
      args:
        APP_ENV: development
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080"
    environment:
      - "APP_ENV=development"
    links:
      - redis:redis
      - postgres:postgres

  worker:
    build:
      context: .
      args:
        APP_ENV: development
    command: celery -A app.tasks worker --loglevel=info --concurrency=5 --pidfile=tmp/%n.pid --logfile=tmp/%n%I.log
    volumes:
      - ./:/usr/src/app
    environment:
      - "APP_ENV=development"
    links:
      - redis:redis
      - postgres:postgres
